module.exports = 
{ id: '0:0:0',
  script_id: 0,
  script_name: '',
  name: '(root)',
  line_number: 0,
  column_number: 0,
  allocations: [],
  child_ids: [ '34:10:10', '34:12:19', '48:573:26', '48:383:24', '48:414:23' ],
  children:
   [ { id: '34:10:10',
       script_id: 34,
       script_name: 'node.js',
       name: '',
       line_number: 10,
       column_number: 10,
       allocations: [],
       child_ids: [ '34:12:19' ],
       children:
        [ { id: '34:12:19',
            script_id: 34,
            script_name: 'node.js',
            name: 'startup',
            line_number: 12,
            column_number: 19,
            allocations: [],
            child_ids: [ '48:573:26' ],
            children:
             [ { id: '48:573:26',
                 script_id: 48,
                 script_name: 'module.js',
                 name: 'Module.runMain',
                 line_number: 573,
                 column_number: 26,
                 allocations: [],
                 child_ids: [ '48:383:24' ],
                 children:
                  [ { id: '48:383:24',
                      script_id: 48,
                      script_name: 'module.js',
                      name: 'Module._load',
                      line_number: 383,
                      column_number: 24,
                      allocations: [],
                      child_ids: [ '48:414:23' ],
                      children:
                       [ { id: '48:414:23',
                           script_id: 48,
                           script_name: 'module.js',
                           name: 'tryModuleLoad',
                           line_number: 414,
                           column_number: 23,
                           allocations: [],
                           child_ids: [ '48:449:33' ],
                           children:
                            [ { id: '48:449:33',
                                script_id: 48,
                                script_name: 'module.js',
                                name: 'Module.load',
                                line_number: 449,
                                column_number: 33,
                                allocations: [],
                                child_ids: [ '48:548:37' ],
                                children:
                                 [ { id: '48:548:37',
                                     script_id: 48,
                                     script_name: 'module.js',
                                     name: 'Module._extensions..js',
                                     line_number: 548,
                                     column_number: 37,
                                     allocations: [],
                                     child_ids: [ '48:481:37' ],
                                     children:
                                      [ { id: '48:481:37',
                                          script_id: 48,
                                          script_name: 'module.js',
                                          name: 'Module._compile',
                                          line_number: 481,
                                          column_number: 37,
                                          allocations: [],
                                          child_ids: [ '59:1:11' ],
                                          children:
                                           [ { id: '59:1:11',
                                               script_id: 59,
                                               script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                               name: '',
                                               line_number: 1,
                                               column_number: 11,
                                               allocations: [],
                                               child_ids: [ '61:5:33' ],
                                               children:
                                                [ { id: '61:5:33',
                                                    script_id: 61,
                                                    script_name: '/Volumes/d/dev/js/sample-heap/example/sample.js',
                                                    name: 'sample',
                                                    line_number: 5,
                                                    column_number: 33,
                                                    allocations: [],
                                                    child_ids: [ '59:12:22' ],
                                                    children:
                                                     [ { id: '59:12:22',
                                                         script_id: 59,
                                                         script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                                         name: 'alloc',
                                                         line_number: 12,
                                                         column_number: 22,
                                                         allocations: [],
                                                         child_ids: [ '60:22:39' ],
                                                         children:
                                                          [ { id: '60:22:39',
                                                              script_id: 60,
                                                              script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                              name: 'flatArray',
                                                              line_number: 22,
                                                              column_number: 39,
                                                              allocations: [],
                                                              child_ids: [ '60:24:21' ],
                                                              children:
                                                               [ { id: '60:24:21',
                                                                   script_id: 60,
                                                                   script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                                   name: 'fillArray',
                                                                   line_number: 24,
                                                                   column_number: 21,
                                                                   allocations: [],
                                                                   child_ids: [ '60:3:26' ],
                                                                   children:
                                                                    [ { id: '60:3:26',
                                                                        script_id: 60,
                                                                        script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                                        name: 'createEmptyArray',
                                                                        line_number: 3,
                                                                        column_number: 26,
                                                                        allocations:
                                                                         [ { count: 2, size: 24 },
                                                                           { count: 210, size: 48 },
                                                                           { count: 1, size: 2088 },
                                                                           { count: 201, size: 8208 },
                                                                           { count: 823, size: 8240 } ],
                                                                        child_ids: [],
                                                                        children: [] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] },
     { id: '34:12:19',
       script_id: 34,
       script_name: 'node.js',
       name: 'startup',
       line_number: 12,
       column_number: 19,
       allocations: [],
       child_ids: [ '48:573:26' ],
       children:
        [ { id: '48:573:26',
            script_id: 48,
            script_name: 'module.js',
            name: 'Module.runMain',
            line_number: 573,
            column_number: 26,
            allocations: [],
            child_ids: [ '48:383:24' ],
            children:
             [ { id: '48:383:24',
                 script_id: 48,
                 script_name: 'module.js',
                 name: 'Module._load',
                 line_number: 383,
                 column_number: 24,
                 allocations: [],
                 child_ids: [ '48:414:23' ],
                 children:
                  [ { id: '48:414:23',
                      script_id: 48,
                      script_name: 'module.js',
                      name: 'tryModuleLoad',
                      line_number: 414,
                      column_number: 23,
                      allocations: [],
                      child_ids: [ '48:449:33' ],
                      children:
                       [ { id: '48:449:33',
                           script_id: 48,
                           script_name: 'module.js',
                           name: 'Module.load',
                           line_number: 449,
                           column_number: 33,
                           allocations: [],
                           child_ids: [ '48:548:37' ],
                           children:
                            [ { id: '48:548:37',
                                script_id: 48,
                                script_name: 'module.js',
                                name: 'Module._extensions..js',
                                line_number: 548,
                                column_number: 37,
                                allocations: [],
                                child_ids: [ '48:481:37' ],
                                children:
                                 [ { id: '48:481:37',
                                     script_id: 48,
                                     script_name: 'module.js',
                                     name: 'Module._compile',
                                     line_number: 481,
                                     column_number: 37,
                                     allocations: [],
                                     child_ids: [ '59:1:11' ],
                                     children:
                                      [ { id: '59:1:11',
                                          script_id: 59,
                                          script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                          name: '',
                                          line_number: 1,
                                          column_number: 11,
                                          allocations: [],
                                          child_ids: [ '61:5:33' ],
                                          children:
                                           [ { id: '61:5:33',
                                               script_id: 61,
                                               script_name: '/Volumes/d/dev/js/sample-heap/example/sample.js',
                                               name: 'sample',
                                               line_number: 5,
                                               column_number: 33,
                                               allocations: [],
                                               child_ids: [ '59:12:22' ],
                                               children:
                                                [ { id: '59:12:22',
                                                    script_id: 59,
                                                    script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                                    name: 'alloc',
                                                    line_number: 12,
                                                    column_number: 22,
                                                    allocations: [],
                                                    child_ids: [ '60:22:39' ],
                                                    children:
                                                     [ { id: '60:22:39',
                                                         script_id: 60,
                                                         script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                         name: 'flatArray',
                                                         line_number: 22,
                                                         column_number: 39,
                                                         allocations: [],
                                                         child_ids: [ '60:24:21' ],
                                                         children:
                                                          [ { id: '60:24:21',
                                                              script_id: 60,
                                                              script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                              name: 'fillArray',
                                                              line_number: 24,
                                                              column_number: 21,
                                                              allocations: [],
                                                              child_ids: [ '60:3:26' ],
                                                              children:
                                                               [ { id: '60:3:26',
                                                                   script_id: 60,
                                                                   script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                                   name: 'createEmptyArray',
                                                                   line_number: 3,
                                                                   column_number: 26,
                                                                   allocations:
                                                                    [ { count: 2, size: 24 },
                                                                      { count: 210, size: 48 },
                                                                      { count: 1, size: 2088 },
                                                                      { count: 201, size: 8208 },
                                                                      { count: 823, size: 8240 } ],
                                                                   child_ids: [],
                                                                   children: [] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] },
     { id: '48:573:26',
       script_id: 48,
       script_name: 'module.js',
       name: 'Module.runMain',
       line_number: 573,
       column_number: 26,
       allocations: [],
       child_ids: [ '48:383:24' ],
       children:
        [ { id: '48:383:24',
            script_id: 48,
            script_name: 'module.js',
            name: 'Module._load',
            line_number: 383,
            column_number: 24,
            allocations: [],
            child_ids: [ '48:414:23' ],
            children:
             [ { id: '48:414:23',
                 script_id: 48,
                 script_name: 'module.js',
                 name: 'tryModuleLoad',
                 line_number: 414,
                 column_number: 23,
                 allocations: [],
                 child_ids: [ '48:449:33' ],
                 children:
                  [ { id: '48:449:33',
                      script_id: 48,
                      script_name: 'module.js',
                      name: 'Module.load',
                      line_number: 449,
                      column_number: 33,
                      allocations: [],
                      child_ids: [ '48:548:37' ],
                      children:
                       [ { id: '48:548:37',
                           script_id: 48,
                           script_name: 'module.js',
                           name: 'Module._extensions..js',
                           line_number: 548,
                           column_number: 37,
                           allocations: [],
                           child_ids: [ '48:481:37' ],
                           children:
                            [ { id: '48:481:37',
                                script_id: 48,
                                script_name: 'module.js',
                                name: 'Module._compile',
                                line_number: 481,
                                column_number: 37,
                                allocations: [],
                                child_ids: [ '59:1:11' ],
                                children:
                                 [ { id: '59:1:11',
                                     script_id: 59,
                                     script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                     name: '',
                                     line_number: 1,
                                     column_number: 11,
                                     allocations: [],
                                     child_ids: [ '61:5:33' ],
                                     children:
                                      [ { id: '61:5:33',
                                          script_id: 61,
                                          script_name: '/Volumes/d/dev/js/sample-heap/example/sample.js',
                                          name: 'sample',
                                          line_number: 5,
                                          column_number: 33,
                                          allocations: [],
                                          child_ids: [ '59:12:22' ],
                                          children:
                                           [ { id: '59:12:22',
                                               script_id: 59,
                                               script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                               name: 'alloc',
                                               line_number: 12,
                                               column_number: 22,
                                               allocations: [],
                                               child_ids: [ '60:22:39' ],
                                               children:
                                                [ { id: '60:22:39',
                                                    script_id: 60,
                                                    script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                    name: 'flatArray',
                                                    line_number: 22,
                                                    column_number: 39,
                                                    allocations: [],
                                                    child_ids: [ '60:24:21' ],
                                                    children:
                                                     [ { id: '60:24:21',
                                                         script_id: 60,
                                                         script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                         name: 'fillArray',
                                                         line_number: 24,
                                                         column_number: 21,
                                                         allocations: [],
                                                         child_ids: [ '60:3:26' ],
                                                         children:
                                                          [ { id: '60:3:26',
                                                              script_id: 60,
                                                              script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                              name: 'createEmptyArray',
                                                              line_number: 3,
                                                              column_number: 26,
                                                              allocations:
                                                               [ { count: 2, size: 24 },
                                                                 { count: 210, size: 48 },
                                                                 { count: 1, size: 2088 },
                                                                 { count: 201, size: 8208 },
                                                                 { count: 823, size: 8240 } ],
                                                              child_ids: [],
                                                              children: [] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] },
     { id: '48:383:24',
       script_id: 48,
       script_name: 'module.js',
       name: 'Module._load',
       line_number: 383,
       column_number: 24,
       allocations: [],
       child_ids: [ '48:414:23' ],
       children:
        [ { id: '48:414:23',
            script_id: 48,
            script_name: 'module.js',
            name: 'tryModuleLoad',
            line_number: 414,
            column_number: 23,
            allocations: [],
            child_ids: [ '48:449:33' ],
            children:
             [ { id: '48:449:33',
                 script_id: 48,
                 script_name: 'module.js',
                 name: 'Module.load',
                 line_number: 449,
                 column_number: 33,
                 allocations: [],
                 child_ids: [ '48:548:37' ],
                 children:
                  [ { id: '48:548:37',
                      script_id: 48,
                      script_name: 'module.js',
                      name: 'Module._extensions..js',
                      line_number: 548,
                      column_number: 37,
                      allocations: [],
                      child_ids: [ '48:481:37' ],
                      children:
                       [ { id: '48:481:37',
                           script_id: 48,
                           script_name: 'module.js',
                           name: 'Module._compile',
                           line_number: 481,
                           column_number: 37,
                           allocations: [],
                           child_ids: [ '59:1:11' ],
                           children:
                            [ { id: '59:1:11',
                                script_id: 59,
                                script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                name: '',
                                line_number: 1,
                                column_number: 11,
                                allocations: [],
                                child_ids: [ '61:5:33' ],
                                children:
                                 [ { id: '61:5:33',
                                     script_id: 61,
                                     script_name: '/Volumes/d/dev/js/sample-heap/example/sample.js',
                                     name: 'sample',
                                     line_number: 5,
                                     column_number: 33,
                                     allocations: [],
                                     child_ids: [ '59:12:22' ],
                                     children:
                                      [ { id: '59:12:22',
                                          script_id: 59,
                                          script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                          name: 'alloc',
                                          line_number: 12,
                                          column_number: 22,
                                          allocations: [],
                                          child_ids: [ '60:22:39' ],
                                          children:
                                           [ { id: '60:22:39',
                                               script_id: 60,
                                               script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                               name: 'flatArray',
                                               line_number: 22,
                                               column_number: 39,
                                               allocations: [],
                                               child_ids: [ '60:24:21' ],
                                               children:
                                                [ { id: '60:24:21',
                                                    script_id: 60,
                                                    script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                    name: 'fillArray',
                                                    line_number: 24,
                                                    column_number: 21,
                                                    allocations: [],
                                                    child_ids: [ '60:3:26' ],
                                                    children:
                                                     [ { id: '60:3:26',
                                                         script_id: 60,
                                                         script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                         name: 'createEmptyArray',
                                                         line_number: 3,
                                                         column_number: 26,
                                                         allocations:
                                                          [ { count: 2, size: 24 },
                                                            { count: 210, size: 48 },
                                                            { count: 1, size: 2088 },
                                                            { count: 201, size: 8208 },
                                                            { count: 823, size: 8240 } ],
                                                         child_ids: [],
                                                         children: [] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] },
     { id: '48:414:23',
       script_id: 48,
       script_name: 'module.js',
       name: 'tryModuleLoad',
       line_number: 414,
       column_number: 23,
       allocations: [],
       child_ids: [ '48:449:33' ],
       children:
        [ { id: '48:449:33',
            script_id: 48,
            script_name: 'module.js',
            name: 'Module.load',
            line_number: 449,
            column_number: 33,
            allocations: [],
            child_ids: [ '48:548:37' ],
            children:
             [ { id: '48:548:37',
                 script_id: 48,
                 script_name: 'module.js',
                 name: 'Module._extensions..js',
                 line_number: 548,
                 column_number: 37,
                 allocations: [],
                 child_ids: [ '48:481:37' ],
                 children:
                  [ { id: '48:481:37',
                      script_id: 48,
                      script_name: 'module.js',
                      name: 'Module._compile',
                      line_number: 481,
                      column_number: 37,
                      allocations: [],
                      child_ids: [ '59:1:11' ],
                      children:
                       [ { id: '59:1:11',
                           script_id: 59,
                           script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                           name: '',
                           line_number: 1,
                           column_number: 11,
                           allocations: [],
                           child_ids: [ '61:5:33' ],
                           children:
                            [ { id: '61:5:33',
                                script_id: 61,
                                script_name: '/Volumes/d/dev/js/sample-heap/example/sample.js',
                                name: 'sample',
                                line_number: 5,
                                column_number: 33,
                                allocations: [],
                                child_ids: [ '59:12:22' ],
                                children:
                                 [ { id: '59:12:22',
                                     script_id: 59,
                                     script_name: '/Volumes/d/dev/js/sample-heap/example/cli.js',
                                     name: 'alloc',
                                     line_number: 12,
                                     column_number: 22,
                                     allocations: [],
                                     child_ids: [ '60:22:39' ],
                                     children:
                                      [ { id: '60:22:39',
                                          script_id: 60,
                                          script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                          name: 'flatArray',
                                          line_number: 22,
                                          column_number: 39,
                                          allocations: [],
                                          child_ids: [ '60:24:21' ],
                                          children:
                                           [ { id: '60:24:21',
                                               script_id: 60,
                                               script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                               name: 'fillArray',
                                               line_number: 24,
                                               column_number: 21,
                                               allocations: [],
                                               child_ids: [ '60:3:26' ],
                                               children:
                                                [ { id: '60:3:26',
                                                    script_id: 60,
                                                    script_name: '/Volumes/d/dev/js/sample-heap/example/allocate.js',
                                                    name: 'createEmptyArray',
                                                    line_number: 3,
                                                    column_number: 26,
                                                    allocations:
                                                     [ { count: 2, size: 24 },
                                                       { count: 210, size: 48 },
                                                       { count: 1, size: 2088 },
                                                       { count: 201, size: 8208 },
                                                       { count: 823, size: 8240 } ],
                                                    child_ids: [],
                                                    children: [] } ] } ] } ] } ] } ] } ] } ] } ] } ] } ] }
