#!/bin/sh

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
ENTRY=${ENTRY:-flamegraph.js}

rm -rf build/bundle.js             && \
git checkout gh-pages              && \
git reset --hard master            && \
make ENTRY=$ENTRY bundle-min       && \
git add -f build/bundle.js         && \
git commit -m "ghp: adding bundle" && \
git push -f origin gh-pages        && \
make clean                         && \
git checkout $CURRENT_BRANCH
